kernel:
  image: "linuxkit/kernel:4.4.78"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/vpnkit-expose-port:e2b49a6c56fbf876ea24f0a5ce4ccae5f940d1be # install vpnkit-expose-port and vpnkit-iptables-wrapper on host
  - linuxkit/init:838b772355a8690143b37de1cdd4ac5db725271f
  - linuxkit/runc:d5cbeb95bdafedb82ad2cf11cff1a5da7fcae630
  - linuxkit/containerd:e33e0534d6fca88e1eb86897a1ea410b4a5d722e

onboot:
  - name: metadata
    image: "linuxkit/metadata:f5d4299909b159db35f72547e4ae70bd76c42c6c"
  - name: sysctl
    image: "linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0"
  - name: sysfs
    image: "linuxkit/sysfs:006a65b30cfdd9d751d7ab042fde7eca2c3bc9dc"
  - name: binfmt
    image: "linuxkit/binfmt:0bde4ebd422099f45c5ee03217413523ad2223e5"
  - name: format
    image: "linuxkit/format:84a997e69051a1bf05b7c1926ab785bb07932954"
  - name: mount
    image: "linuxkit/mount:ac8939c4102f97c084d9ddfd445c1908fce6d768"
    command: ["/mount.sh", "/var/vcap"]
  - name: mount-vpnkit
    image: "alpine:3.6"
    binds:
      - /var/:/host_var:rbind,rshared
    capabilities:
      - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir -p /host_var/vpnkit/port && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
  - name: dhcpcd
    image: "linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: acpid
    image: "linuxkit/acpid:1966310cb75e28ffc668863a6577ee991327f918"
  - name: getty
    image: "linuxkit/getty:894eef1e5f62f3bc31de8ffaff2b6c0e093c4595"
    env:
      - INSECURE=true
  - name: ntpd
    image: "linuxkit/openntpd:2874b66c9fa51fa5b4d11c8b50441eb94ee22a5a"
  - name: vsudd
    image: "linuxkit/vsudd:adad4b6ab7529b6b95339eb0752b0c81a218d185"
    binds:
      - /var/run:/var/run
    command: ["/vsudd", "-inport", "2376:unix:/run/containerd/containerd.sock"]
  - name: vpnkit-forwarder
    image: "linuxkit/vpnkit-forwarder:9c1545e7b093d1210118de7661d7346393ec195b"
    binds:
      - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder", "-vsockPort", "62373"]

trust:
  org:
    - linuxkit
