#!/bin/bash

BOSH=bosh

if which gobosh; then
  BOSH=gobosh
fi

set -e
git submodule update --init --recursive

stemcell_path=~/Downloads/bosh-stemcell-3445.2-warden-boshlite-ubuntu-trusty-go_agent.tgz

if ! [ -f "${stemcell_path}" ]; then
  curl -o "${stemcell_path}" -L -J https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=3445.2
fi


$BOSH us "${stemcell_path}"
$BOSH ucc -n cf-deployment/bosh-lite/cloud-config.yml

$BOSH -d cf deploy cf-deployment/cf-deployment.yml \
  -v system_domain=bosh-lite.com --vars-store=./creds.yml \
  -o cf-deployment/operations/use-compiled-releases.yml \
  -o cf-deployment/operations/experimental/use-grootfs.yml \
  -o cf-ops-files/cfkit.yml \
  -o cf-ops-files/cfkit-grootfs.yml \
  -n

