#!/bin/bash

set -e
gobosh us ~/Downloads/bosh-stemcell-3421.11-warden-boshlite-ubuntu-trusty-go_agent.tgz
gobosh ucc -n ../cf-deployment/bosh-lite/cloud-config.yml

gobosh -d cf deploy ~/workspace/cf-deployment/cf-deployment.yml \
  -v system_domain=bosh-lite.com --vars-store=./creds.yml \
  -o ~/workspace/cf-deployment/operations/use-compiled-releases.yml \
  -o ~/workspace/cf-deployment/operations/experimental/use-grootfs.yml \
  -o ~/workspace/cf-deployment/operations/bosh-lite.yml \
  -n

